name: webview_jsbridge
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/KouYiGuo/webview_jsbridge

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
